
dataset:
  log_file: data/splited data/9-256x1024/Linux_1.txt
model:
  PROJECT_ID : log-analysis-433902
  LOCATION : "us-central1"
  # LOCATION : "asia-east1"
  # LOCATION : asia-east2
  MODEL_NAME : gemini-1.5-pro
  temperature: 0
  top_p: 0.8
inference:
  save_path: result
  chunk_size: 
  count: True
  prompt: prompt_oneshot
test:
  llm_result_file: result/128k-18-result/merge_128k_18.json
  re_result_file: data/result-re_Linux.json
  human_result_file: data/human_evaluation.json
comment: "128k-18- all file eval"

