
dataset:
  log_file: "data/splited data/18-128x1024/Linux_3.txt"
model:
  PROJECT_ID : "log-analysis-433902"
  # LOCATION : "us-central1"
  LOCATION : "asia-east1"
  # LOCATION : "asia-east2"
  MODEL_NAME : "gemini-1.5-pro"
  temperature: 0
  top_p: 0.8
inference:
  save_path: "result"
  chunk_size:
  count: False
  prompt: prompt_extract
test:
  llm_result_file: "result/result_2024-09-03_14-46-46_192k file1_counts/inference_output/output0.json"
  re_result_file: "data/splited data/12-192x1024/new_result_human_Linux_1.json"
  human_result_file: "data/splited data/18-128x1024/result_huaman_Linux_3.json"
comment: "128k file3 extract t=0 top_p=0.8"

